apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
data:
  db_user: cm9vdA==
  db_pass: cm9vdA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configs
data:
  db_host: mongodb
  db_port: "27017"
  db_name: teste
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb-app
        image: mongo-app:v1
        ports:
        - containerPort: 8080
        env:
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: db_user
          - name: DATABASE_PASS
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: db_pass
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: app-configs
                key: db_host
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: app-configs
                key: db_port
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: app-configs
                key: db_name
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-app
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 8080
  selector:
    app: mongo
